export const UserActionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_Fail: 'LOGIN_Fail',
    LOGIN_LOADED: 'LOGIN_LOADED',
    SIGNUP_LOADED: 'SIGNUP_LOADED',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAIL: 'SIGNUP_FAIL',
    USER_LOADED_SUCCESS: 'USER_LOADED_SUCCESS',
    USER_LOADED_FAIL: 'USER_LOADED_FAIL',
    USER_LOADED_LOADING: 'USER_LOADED_LOADING',

}